version: '3'
services:
  front-end:
    image: "pesegal/mc-front-end:0.0.1"
    container_name: front-end
    networks:
      - mc-net
    ports:
      - "3000:8080"
    environment:
      SERVICE_COUNT_HOST: "http://count-service"
      SERVICE_COUNT_PORT: 8081
      SPRING_CLOUD_CONSUL_HOST: "http://consul"
      # Note ports only bind between container -> host, not container -> container
      # Therefore, use app.prop configured server.port for count-service

    depends_on:
      - consul

  count-service:
    image: "pesegal/mc-count-service:0.0.1"
    networks:
      - mc-net
    ports:
      - "8081" # Switch this to random port mapping to allow for --scale

    environment:
      SPRING_CLOUD_CONSUL_HOST: "http://consul"
      SPRING_CLOUD_CONSUL_DISCOVERY_INSTANCEID: '$${spring.application.name}:$${random.value}'

    depends_on:
      - consul

# Dynamic Configuration Settings
  git2consul:
    image: "cimpress/git2consul"
    container_name: git2consul

    entrypoint:
      - "/usr/bin/node"
      - "/usr/lib/node_modules/git2consul"
      - "--config-file"
      - "/etc/git2consul.d/config.json"

    environment:
      CONSUL_ENDPOINT: 'consul'
      CONSUL_PORT: '8500'

    volumes:
      - "${PWD}/configRepo/git2consul_config.json:/etc/git2consul.d/config.json"
      - "${PWD}/configRepo/appConfig:/var/repo"

    networks:
      - mc-net

    depends_on:
      - consul

  consul:
    hostname: consul
    image: "consul"

    container_name: consul-dev
    networks:
      - mc-net
    ports:
      - "8500:8500"
      - "8600:8600"

networks:
  mc-net:
    driver: bridge


